# Generated by Django 4.2.7 on 2023-12-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_specialist_doctor_profile_waiting_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Assess',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=10, null=True),
        ),
    ]
