# Generated by Django 4.2.7 on 2023-12-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_assess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Assess',
            field=models.CharField(blank=True, choices=[('1', '1'), ('11', '2'), ('111', '3'), ('1111', '4'), ('11111', '5')], max_length=10, null=True),
        ),
    ]
