# Generated by Django 4.2.7 on 2023-12-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_assess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Assess',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
