# Generated by Django 4.2.7 on 2023-12-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_assess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Assess',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
