# Generated by Django 4.2.7 on 2023-12-20 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_assess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Assess',
        ),
    ]
