# Generated by Django 4.2.7 on 2023-12-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doctor_in',
            field=models.CharField(blank=True, choices=[('مخ و اعصاب', 'مخ و اعصاب'), ('نساء وتوليد', 'نسا وتوليد'), ('أسنان', 'أسنان'), ('اطفال', 'اطفال')], max_length=50, null=True),
        ),
    ]
