# Generated by Django 4.2.7 on 2023-12-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_create_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_post',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
