# Generated by Django 4.2.7 on 2023-12-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_create_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_post',
            name='subject',
            field=models.TextField(verbose_name='الموضوع'),
        ),
        migrations.AlterField(
            model_name='create_post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='العنوان'),
        ),
    ]
