# Generated by Django 4.2.7 on 2023-12-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_create_post_subject_alter_create_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_post',
            name='image',
            field=models.ImageField(default=1, upload_to='Post/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
