# Generated by Django 4.2.7 on 2023-12-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_create_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_post',
            name='image',
            field=models.ImageField(upload_to='Post/%y/%m/%d', verbose_name='الصورة'),
        ),
    ]
