# Generated by Django 4.2.7 on 2023-12-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_create_post_slug_alter_create_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_post',
            name='slug',
        ),
    ]
