# Generated by Django 4.2.7 on 2023-12-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_create_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_post',
            name='Introduction',
            field=models.TextField(default=1, verbose_name='المقدمة'),
            preserve_default=False,
        ),
    ]
